### ISSUE TITLE
Serious bug: char*-valued functions that return nullptr make system go BOOM

### ISSUE THREAD

**Issue by rpatters1** [kunitoki/LuaBridge3#107]
I have finally nailed down the actual situation that is causing a breaking change in my scripts. I apologize for two previous long-winded issues that were wrong (and now closed).

Consider this class and its registration:

```c++
class foo
{
public:
   foo() {}
   const char * nullconst() { return nullptr; }
   char * null() { return nullptr; }
   void twochars (const char* one, const char* two = nullptr)
   {
      std::string one_two = one;
      if (two) one_two += " another parameter was provided: " + two;
   }
};

   luabridge::getGlobalNamespace(L)
     .beginNamespace("foobar")
        .beginClass<foo>("foo")
           .addConstructor<void(*)(void)>()
           .addFunction("nullconst", &foo::nullconst)
           .addFunction("null", &foo::null)
           .addFunction("twochars", &foo::twochars)
        .endClass()
     .endNamespace();
```

Now consider the following Lua:

```lua
local foo = foobar.foo()
local nullconst = foo:nullconst() -- nullconst comes back nil on LB2 but "" on LB3: this is a breaking change
local null = foo:null() -- null doesn't come back. system goes >>BOOM<< on both LB2 and LB3
```

See comments. My opinion is that both local variables `nullconst` and `null` should be `nil` after this code runs.

**Comment by rpatters1** [comment]
I edited the original description to add the `twochars` function to illustrate another breaking change from LB2 that is related. The 2nd parameter of `twochars` is optional in C++ and takes `nullptr` as the default. With LB2 it is possible to call this function as

```lua
foo:twochars("aaa", nil)
```

However on LB3 it receives a runtime error: "Error decoding argument #3: The lua object can't be cast to desired type". This does not seem acceptable to me. To support the `twochars` function, I have to either modify it to handle empty strings like nullptr, which is not possible (or at least undesirable) with 3rd party libraries. Or I have to find all the needles in my haystack that need proxy functions.

I don't think this is an acceptable breaking change.

**Comment by kunitoki** [comment]
Fixed in latest master
