### ISSUE TITLE
Codesmell: luabridge::enableExceptions uses static global boolean

### ISSUE THREAD

**Issue by rpatters1** [kunitoki/LuaBridge3#109]
For background: in the Lua on Finale environment, each client gets a separate Lua state. It is possible for multiple states to be active at once, even though they all run in the main U.I. thread. The main reasons this happens are:

- the script retains its state to keep context such as expensive global variable initialization or dialog box context.
- the script runs a modeless dialog box.
- a script executes another script (in a separate Lua state) through a mechanism provided by the Lua Finale plugin.

The codesmell comes from the fact that luabridge::enableExceptions affects all Lua states but appears to only affect one. I would be cool with any of the following:

- a `luabridge::enableExceptions()` call (no Lua state) that I could run once when my program initializes.
- a compile option (`#define` statement) to specify the option rather than a static boolean.
- storing the enableExceptions choice in the Lua state somewhere instead of a static boolean.

This was not an issue with LB2, because its version of `luabridge::enableExceptions` just calls `lua_atpanic` and is done. The current LB3 implementation is a combination of state-dependent calls and non-state-dependent calls, and that seems like codesmell to me.

**Comment by kunitoki** [comment]
Yes i don't like those globals, enableExceptions, hideMetatables... they're awful and tech debt. Will eventually get rid of them. If you'll enable exceptions in the compiler you will get exceptions enabled in luabridge, and otherwise if no exception are compiled in.

**Comment by rpatters1** [comment]
> If you'll enable exceptions in the compiler you will get exceptions enabled in luabridge

I can't tell if you are expressing a goal for the future. If so, right on. But just so we're understanding each other, that isn't how it works now.

**Comment by kunitoki** [comment]
Should be fixed in the latest master

**Comment by kunitoki** [comment]
Yes this is my desire for the future, if you compile with exceptions on i suppose than you are fine them being thrown.
