### ISSUE TITLE
Question about `luabridge::setHideMetatables`

### ISSUE THREAD

**Issue by rpatters1** [kunitoki/LuaBridge3#113]
I am trying to understand a difference between LB2 and LB3 concerning metatable security. I have released into the wild an experimental version of the Lua plugin for Finale built with LB3. Almost immediately I got a show stopper report from a user that is caused by the fact that `getmetatable` returns false instead of the metatable for my framework classes.

After digging into the code, it seems I could call `luabridge::setHideMetatables(false)` in my initialization routine. At any rate, that fixes the problem. But it raises two questions:

- Why did it ever work on LB2? Did LB3 fix a bug in LB2's security mechanism? I remember having looked at this code in LB2 before and wondering why I could still get the metatable.
- What are the security implications of `luabridge::setHideMetatables(false)` ? Keeping in mind that all scripts run in separate Lua states on my system, it doesn't seem like a malicious script could cause harm to another script. Put another way, if it's malicious, it should not be possible for it to make it appear that *another* script is the culprit.

There is an entire edifice of mixin libraries at the [Finale Lua scripts](https://github.com/finale-lua/lua-scripts) repo that depends on acquiring the metatable for a class instance. It is extremely convenient and powerful. But before I blindly disable the hiding of metatables, I would like to understand why I didn't need to do this in LB2 and what the security implications are.

**Comment by Mellnik** [comment]
It was broken all the time in vanilla LB. I discovered it (See PR 309 in LB2) and kunitoki patched it in LB3.

I can't give you a deep explanation but untrusted code should never be able to modify the metatable of a userdata type. Even if it is just for the sake of `__gc`.

**Comment by rpatters1** [comment]
Is there a way to provide read-only access to the metatable?

**Comment by rpatters1** [comment]
FWIW: the code I'm looking at is forwarding calls to `__index` and `__newindex`. Nothing to do with `__gc`. Is there some safer way you could suggest to make this possible>

**Comment by kunitoki** [comment]
We could try just preventing __newindex in class metatables, but i don't know about any possible side effects or in general other implications we could introduce, i might need to test this a bit more.

**Comment by rpatters1** [comment]
I'm wondering if the LuaBridge library should do anything (beyond making hide mts optional as it does now.) If I can provide forwarding functions, that might be all that's needed.

**Comment by rpatters1** [comment]
On thing that occurs to me is that it might be nice if this setting were available on a per-Lua state basis instead of global. In my environment I could imagine it being something that the user (or configuration) authorizes.

**Comment by kunitoki** [comment]
I'm allowing this per class instead

**Comment by kunitoki** [comment]
I've moved this to a per class / namespace, see the upcoming PR for extensible classes (i've added there options for classes and namespaces) https://github.com/kunitoki/LuaBridge3/blob/49ddf4f0ef3cc1210b38de75c56ac53f019b1a64/Tests/Source/ClassTests.cpp#L2968-L2993
