### ISSUE TITLE
Report file and line number info when property assignment causes runtime error

### ISSUE THREAD

**Issue by rpatters1** [kunitoki/LuaBridge3#118]
A while back I posted [this issue](https://github.com/vinniefalco/LuaBridge/issues/294) on the OG LuaBridge repo. @kunitoki reported on that conversation thread that it was fixed in LB3. Here is a situation where I am seeing a similar issue in LB3:

```c++
struct foo
{
   std::string str;
   const char * get_string() const { return str.c_str(); }
   void set_string(const char *val) { str = val; }
};

   luabridge::getGlobalNamespace(L)
         .beginClass<foo>("foo")
            .addConstructor<void(*)()>()
            .addProperty("String", &foo::get_string, &foo::set_string)
         .endClass();
```
```lua
local v = 12
local myfoo = foo()
myfoo.String = v
```

The property assignment above gets the error "Error decoding argument 2: The lua object can't be cast to desired type". However, there is no file or line number info.

**Comment by kunitoki** [comment]
If you do the same with a method you get file and line numbers ?

**Comment by rpatters1** [comment]
Yes, if I register the function and call it, I get file/line num:

```c++
   luabridge::getGlobalNamespace(L)
         .beginClass<foo>("foo")
            .addConstructor<void(*)()>()
            .addProperty("String", &foo::get_string, &foo::set_string)
            .addFunction("set_string", &foo::set_string)
         .endClass();
```

```lua
local v = 12
local myfoo = foo()
myfoo.set_string(v) --> error with file/line num
myfoo.String = v --> error with no file or line num
```

**Comment by kunitoki** [comment]
There's also a problem with luau vs vanilla lua, they behave differently. Luau for example reports it already in that circumstance + throws the panic handler, which means i get double locations `"[string "..."]:3: "[string "..."]:3: Error decoding argument 1: The lua object can't be cast to desired type"`
