### ISSUE TITLE
Question: supplying C++ user data

### ISSUE THREAD

**Issue by rpatters1** [kunitoki/LuaBridge3#122]
I am binding [`tinyxml2`](https://github.com/leethomason/tinyxml2) to Lua with LuaBridge. It has a getter and setter for user data, which is just a `void *` allocated by the caller and returned to the caller when requested. The caller is entirely responsible for its lifetime. The framework itself does nothing with it.

I was thinking it would be nice to store a LuaRef in this variable for Lua clients. (This could be done in a proxy function for SetUserData.) I'm guessing what I would store is the index into the Lua registry (`m_ref`). My questions are:

- is this even possible?
- if so, is it a good idea?

Some requirements would be that on the proxy function for GetUserData, I would have to

- reconstitute the LuaRef from the registry index.
- return nil if the underlying LuaRef has been garbage collected.

My Lua API programming skills are not the most sophisticated, so I apologize if there is an obvious answer to these. If there is no easy answer, I can omit these APIs from the binding.

**Comment by kunitoki** [comment]
Can you provide an example usage of this pointer from lua ?

**Comment by rpatters1** [comment]
To further flesh it out, here is a hypothetical outline of the proxy functions in C++ that I was imagining:

```c++
int proxySetter(lua_State* L)
{
   tinyxml2::XMLNode* node = luabridge::Stack<tinyxml2::XMLNode*>::get(L, 1).value();
   luabridge::LuaRef data = luabridge::Stack<luabridge::LuaRef>::get(L, 2).value();
   int ref = ??? // do some magic with the LuaRef, presumably to get the Lua registry index. not sure.
   node->SetUserData(reinterpret_cast<void*>(ref));
   return 0;
}

int proxyGetter(lua_State *L)
{
   const tinyxml2::XMLNode* node = luabridge::Stack<const tinyxml2::XMLNode*>::get(L, 1).value();
   int ref = reinterpret_cast<int>(node->GetUserData());
   if (!ref)
      lua_pushnil(L);
   else
   {
      luabridge::LuaRef data = ??? // do some magic with the ref to hydrate a LuaRef from the Lua registry index
      // if it has been garbage collected, we push nil, otherwise:
      luabridge::Stack<luabridge::LuaRef>::push(L, data).throw_on_error();
   }
   return 1;
}

**Comment by kunitoki** [comment]
Maybe that will not work as you want to keep the value alive, but only if the key is not expired (and the key should be the userdata).

```cpp

// Setup
lua_newtable(L);
lua_newtable(L);
lua_pushstring(L, "k");
lua_setfield(L, -2, "__mode");
lua_setmetatable(L, -2);
lua_setfield(L, LUA_REGISTRYINDEX, "__xml_user_data");

// Set
lua_getfield(L, LUA_REGISTRYINDEX, "__xml_user_data");
lua_pushvalue(L, 1); // the tinyxml2::XMLNode* as key
lua_pushvalue(L, 2); // the lua object you want to store as value
lua_settable(L, -3);

// Get
lua_getfield(L, LUA_REGISTRYINDEX, "__xml_user_data");
lua_pushvalue(L, 1); // the tinyxml2::XMLNode* as key
lua_gettable(L, -2);
```

**Comment by kunitoki** [comment]
See http://lua-users.org/wiki/WeakTablesTutorial for some ideas

**Comment by rpatters1** [comment]
Thanks for all the ideas. I'll ponder it and give it more study. It may not make v1. I'm not sure how useful the feature in `tinyxml2` is, in any case.
