### ISSUE TITLE
Error when trying to print metatable

### ISSUE THREAD

**Issue by dtroitskiy** [kunitoki/LuaBridge3#130]
We discovered small issue.
When you have any bound class with `visibleMetatables` enabled like this:
```
getGlobalNamespace(L)
  .beginClass<Test>("Test", visibleMetatables)
  // ...
```
And then in Lua you try to do this:
```
local mt = getmetatable(Test)
for k, v in pairs(mt) do
  print(('%s - %s'):format(k, v))
end
```
It ends up in some kind of assertion failure or something.
Exact line in LuaBridge which gives error is in `CFunctions.h` line 515:
```
template <class C>
static int tostring_metamethod(lua_State* L)
{
    Userdata* ud = Userdata::getExact<C>(L, 1);
    LUABRIDGE_ASSERT(ud);

    lua_getmetatable(L, -1); // Stack: metatable (mt) <--- FAILS HERE!
```
Maybe it's because bound class metatables have some other tables in them and these tables don't have metatable, but here it's tried to be accessed to find `__tostring` metamethod to print it.
So I'm not sure whether it's an actual issue, or it's better to not attempt to print metatables like this. But at least I think there should be some way to avoid this error.

**Comment by kunitoki** [comment]
Fixed in https://github.com/kunitoki/LuaBridge3/commit/097d5e6a906fd39159b22c08d03fcda8c1ef7c43
