### ISSUE TITLE
void* problem when addConstructor and addFunction

### ISSUE THREAD

**Issue by venjin** [kunitoki/LuaBridge3#135]
when the return type is void*, addFunction will compile fail in **push**:
```CPP
template <class T>
struct StackOpSelector<const T*, false>
{
    using ReturnType = TypeResult<T>;

    static Result push(lua_State* L, const T* value) { return Stack<T>::push(L, *value); }

    static ReturnType get(lua_State* L, int index) { return Stack<T>::get(L, index); }

    static bool isInstance(lua_State* L, int index) { return Stack<T>::isInstance(L, index); }
};
```
What should i do to solve this problem?
I can not modify the return type from void* to another because it is a third library.

**Comment by kunitoki** [comment]
What do you want to do with the void* in lua land ? Is it an opaque pointer ? I suggest you wrap it in a cfunction compatible lambda and push a lightuserdata in lua land instead

**Comment by kunitoki** [comment]
What i mean is how do you expect it to work on lua side ? if you assign this pointer to lua it needs to be marshalled over a structured type so luabridge can know what it is and how set and retrieve it from the stack. You could use an inline lambda instead of a function.

**Comment by kunitoki** [comment]
I added support in #138 for `void*` and `const void*` as lightuserdata, it's up to you to make good use of it.

**Comment by venjin** [comment]
> I added support in #138 for `void*` and `const void*` as lightuserdata, it's up to you to make good use of it.

ok, thanks a lot!!!
