### ISSUE TITLE
`LuaRef::isInstance()` fails on const references

### ISSUE THREAD

**Issue by dtroitskiy** [kunitoki/LuaBridge3#137]
Another issue I noticed some time ago, but with that extensible class stuff we were busy recently I didn't have time to post it before.

So, in my code I have class methods that accept `LuaRef` and check what object they actually store using `LuaRef::isInstance<Something>()`.
By the way, I was pleasantly surprised it works even on `shared_ptr`s for objects, that's really convenient.
But turned out it doesn't work well when `LuaRef` references an object that is `const Something&` originally.
I composed full example like this.
C++:
```C++
#include <string>

#include "luaState.h"
#include "loadScript.h"
#include "luabridge/LuaBridge.h"

using std::string;

using namespace luabridge;

class Foo
{
public:
  inline Foo() {}
  inline Foo(const string& name) : name(name) {}

  inline const string& getName() const { return name; }

  static const Foo& createConstRef(const string& name)
  {
    static Foo instance(name);
    return instance;
  }

private:
  string name;
};

class Bar
{
public:
  inline Bar() {}

  void setFoo(const LuaRef& ref)
  {
    if (ref.isInstance<Foo>())
    {
      foo = ref.cast<Foo>().value();
    }
  }

  inline const string& getFooName() const { return foo.getName(); }

private:
  Foo foo;
};

int main()
{
  const auto L = getLuaState();
  registerMainThread(L);
  enableExceptions(L);

  getGlobalNamespace(L)
    .beginClass<Foo>("Foo")
      .addConstructor<void(*)(const string&)>()
      .addStaticFunction("createConstRef", &Foo::createConstRef)
      .addFunction("__tostring", +[](Foo& self)
      {
        return self.getName();
      })
    .endClass()
    .beginClass<Bar>("Bar")
      .addConstructor<void(*)()>()
      .addFunction("setFoo", &Bar::setFoo)
      .addFunction("getFooName", &Bar::getFooName)
    .endClass();

  loadScript("test.lua");

  return 0;
}
```
Lua:
```Lua
local fooFirst = Foo('first')
local fooSecond = Foo.createConstRef('second')

local bar = Bar()

bar:setFoo(fooFirst)
print(bar:getFooName())

bar:setFoo(fooSecond)
print(bar:getFooName())

print(fooFirst)
print(fooSecond)
```
So what happens here is that `fooFirst` is created as a regular object, and `fooSecond ` is created with `const Foo&`. And when `fooSecond` is passed to `Bar::setFoo()`, calling `ref.isInstance<Foo>()` on it doesn't return true. At the same time, if you still try to cast it to that type without checking, it will work no problem.

Another thing, looks like metamethods aren't called correctly for const refs. Because, as you can see, I defined `__tostring`, but it will work only for `fooFirst` and not for `fooSecond`. `print(fooSecond)` will just print `userdata: ...`.

**Comment by kunitoki** [comment]
I think we might get the same problem with pointers, seems to be a constness issue

**Comment by kunitoki** [comment]
Give it a spin on the branch #136 

I've added your test there and now it's passing https://github.com/kunitoki/LuaBridge3/pull/136/files#diff-cd70549e26a819fe4ab5502e1e783320b16be7b19c74582267b8cc90b73943e7R205-R236

**Comment by dtroitskiy** [comment]
Yep, works now, thanks a lot!

**Comment by dtroitskiy** [comment]
@kunitoki, can you please reply here as well on my last comment? I just wonder whether this cast to const ref should be okay thing to do or not. Because if it's okay, then probably there shouldn't be compilation errors.

**Comment by kunitoki** [comment]
Well Expected doesn't fully support references by design, i can see what i can do there. In general, pointers work much better in that regard

**Comment by dtroitskiy** [comment]
Has to re-open this issue because another problem has been discovered.
Though interesting thing, that problem only appears on classes with `extensibleClass` enabled, and the actual crash occurs in `try_call_index_extensible()` in `CFunctions.h`, but at the same time it appears only on const ref classes. So maybe I could also post this comment to extensible classes issue, but I'm not sure.

So, to reproduce it, you just need to bind a new property to the class that is accessed as const reference. With example code above (and I recall you used the same in your test) you can do:
```C++
.beginClass<Foo>("Foo", extensibleClass)
  .addConstructor<void(*)(const string&)>()
  .addStaticFunction("createConstRef", &Foo::createConstRef)
  .addProperty("name", &Foo::getName)
```
and yeah, `extensibleClass` is also required here for reproduction.
Then in Lua you just do:
```Lua
local foo = Foo.createConstRef('test')
print(foo.name)and yeah, `extensibleClass` is also required here for reproduction.
Then in Lua you just do:
```Lua
local foo = Foo.createConstRef('test')
print(foo.name)
```
and you end up in `try_call_index_extensible()` at line `rawgetfield(L, -1, key); // Stack: mt, st, ifbresult | nil`.

And just now, while I was testing it more, I found out that trying to access non-existent property leads to the same.

**Comment by kunitoki** [comment]
I pushed a set of fixes for it in https://github.com/kunitoki/LuaBridge3/pull/136

**Comment by dtroitskiy** [comment]
Yep, all good now, thanks!
