### ISSUE TITLE
TypeResult<T> does not expose valueOr() convenience method

### ISSUE THREAD

**Issue by matrix47** [kunitoki/LuaBridge3#141]
Reference manual has this part about safe type casting:
```
void passString (std::string);

luabridge::LuaRef v (L);

// The following is safe and will never throw exceptions or call the lua panic handler.

passString (v.cast<std::string> ().valueOr ("fallback"));
```
But it doesn't seem like TypeResult<T> has `valueOr()` method, only the contained Expected<T> has it, but it is not exposed via TypeResult. Or am I missing something?
Thanks a lot!

**Comment by kunitoki** [comment]
You right, this has not been exposed. Will try to add it, thanks for reporting
