### ISSUE TITLE
`makeUnexpected()` in `Set.h` causes compilation errors

### ISSUE THREAD

**Issue by dtroitskiy** [kunitoki/LuaBridge3#144]
Seems a tiny issue. I already fixed it locally by just removing these calls.

So in `Set.h` the code was like this:
```C++
    [[nodiscard]] static TypeResult<Type> get(lua_State* L, int index)
    {
        if (!lua_istable(L, index))
            return makeUnexpected(makeErrorCode(ErrorCode::InvalidTypeCast));

        const StackRestore stackRestore(L);

        Type set;

        int absIndex = lua_absindex(L, index);
        lua_pushnil(L);

        while (lua_next(L, absIndex) != 0)
        {
            auto item = Stack<K>::get(L, -1);
            if (! item)
                return makeUnexpected(makeErrorCode(ErrorCode::InvalidTypeCast));

            set.emplace(*item);
            lua_pop(L, 1);
        }

        return set;
    }
```
And then if I bound some method of a class that had signature `void setSomething(const std::set<std::string>& something)`, I got a bunch of compilation errors with a lot of output.
I then checked other `std` container wrapper headers like `List.h`, `Map.h` and found out they don't have `makeUnexpected()`, only `makeErrorCode()`. I then removed `makeUnexpected()` and the errors were gone.

**Comment by matrix47** [comment]
I concur, and I've proposed a merge request to fix this too: https://github.com/kunitoki/LuaBridge3/pull/143

**Comment by kunitoki** [comment]
Sorry but vacations took over 🍹

Will fix it as soon as i get back to the laptop, we are missing unit tests for it ;)
