### ISSUE TITLE
Namespace registration fails on assert when split across separate calls

### ISSUE THREAD

**Issue by failsafe89** [kunitoki/LuaBridge3#147]
The following code works as expected

```
getGlobalNamespace(L)
        .beginNamespace("TEST")
        .beginNamespace("detail")
        .endNamespace()
        .beginNamespace("utility")
        .endNamespace()
        .endNamespace();
```

but when rewritten with a temporary local holding the namespace between each call (which works in LuaBridge 2), eg.

```
    Namespace ns = getGlobalNamespace(L);
    ns = ns.beginNamespace("TEST");
    ns = ns.beginNamespace("detail");
    ns = ns.endNamespace();
    ns = ns.beginNamespace("utility");
    ns = ns.endNamespace();
    ns = ns.endNamespace();
```

Causes a crash by failing an assert in the Namespace constructor call in beginNamespace
https://github.com/kunitoki/LuaBridge3/blob/79775a8810636dd1b60353cfef7288acf4f53db8/Source/LuaBridge/detail/Namespace.h#L1524-L1528

For the life of me I can't work out why the code would produce different results

To provide context, this pattern is useful of you want to populate nested namespaces in dynamic way
```
Namespace populate_detail(Namespace ns)
{
    ns = ns.beginNamespace("detail");
    // ... do stuff in the namespace
    return ns.endNamespace();
}

Namespace populate_utility(Namespace ns)
{
    ns = ns.beginNamespace("utility");
    // ... do stuff in the namespace
    return ns.endNamspace();
}

Namespace ns = getGlobalNamespace(L).beginNamespace("TEST");
// Imagine looping through a vector of registration functions
ns = populate_detail(ns);
ns = populate_utility(ns);
ns.endNamespace();
```

**Comment by kunitoki** [comment]
That is strange, i suppose some stuff in the Registrar base class is failing on copy assignment. Will give it a fix.
