### ISSUE TITLE
C++ functions that take null pointer arguments

### ISSUE THREAD

**Issue by rpatters1** [kunitoki/LuaBridge3#149]
I am hooking up a C++ function that has an optional null pointer. This is legacy code. Modern C++ would likely be using `std::optional` or something. My function has something like this pattern:

```c++
void MyFunc(const MyStringClass* msg = NULL)
{
    MyStringClass actualMsg(msg ? *msg : MyStringClass("default message"));
    ... // do something with actualMsg
}
```

My recollection is that LuaBridge2 would allow this:

```lua
MyFunc(nil)
```
Unfortunately that produces a runtime error on LuaBridge3, and the only current workaround seems to be the very ugly:

```lua
local mystring = MyStringClass()
mystring.String = "default message" -- yes the library string class requires two steps to initialize string - facepalm
MyFunc(mystring)
```

Obviously I can provide a special CFunction to hook up this particular method, but the issue may be fairly widespread. I'm wondering if @kunitoki sees any reason for LuaBridge3 to provide a general solution (even if optionally).

**Comment by kunitoki** [comment]
That should work, i tested it right now:

```cpp
struct MyStringClass
{
    MyStringClass(const char* msg)
        : msg_(msg)
    {
    }

    std::string msg_;
};

std::string MyFunc(const MyStringClass* msg = nullptr)
{
    MyStringClass actualMsg (msg ? *msg : MyStringClass("default message"));
    return actualMsg.msg_;
}    

TEST_F(ClassTests, NilCanBeConvertedToNullptr)
{
    luabridge::getGlobalNamespace(L)
        .addFunction("MyFunc", MyFunc)
        .beginClass<MyStringClass>("MyStringClass")
        .endClass();
    
    MyStringClass custom("custom message");
    luabridge::setGlobal(L, &custom, "custom");

    runLua("result = MyFunc(custom)");
    EXPECT_EQ("custom message", result<std::string>());
    
    runLua("result = MyFunc(nil)");
    EXPECT_EQ("default message", result<std::string>());
}
```

Is there anything special you are doing in the registration code ?

**Comment by rpatters1** [comment]
Auggh. I added the `nil` to the wrong line of Lua code in the original program. It was totally user error. That will teach me to work late at night. Thank you for looking into it for me.
