### ISSUE TITLE
Recent LB3 Change Causes my code not to compile.

### ISSUE THREAD

**Issue by rpatters1** [kunitoki/LuaBridge3#155]
A recent change to LB3 has caused my code not to compile. Specifically, it fails because the copy constructors have been deleted from the registration classes.

I have code that builds up each class with repeated calls using the `refl-cpp` reflection framework for C++. The function signature for the function that registers the methods and properties is:

```c++
template<class T, typename TN>
void AddClassMembers(TN& bridgeClass, const char* className)
{...}
```

The code that creates the class does this:

```c++
   auto bridgeClass = luabridge::getGlobalNamespace(l)
                        .beginNamespace (nameSpace.c_str())
                           .beginClass<T>(name.c_str() LB3_PARM(options))
                              .template addConstructor<ConstructorArgs>();

   AddClassMembers<T>(bridgeClass, name.c_str());

   bridgeClass.endClass()
      .endNamespace();
```

The deleted copy constructors mean the assignment of `bridgeClass` fails to compile. I modified the code as follows (after examining the LB3 changes) to use && references:

```c++
template<class T, typename TN>
void AddClassMembers(TN&& bridgeClass, const char* className)
{...}
```

```c++
   auto&& bridgeClass = luabridge::getGlobalNamespace(l)
                        .beginNamespace (nameSpace.c_str())
                           .beginClass<T>(name.c_str() LB3_PARM(options))
                              .template addConstructor<ConstructorArgs>();

   AddClassMembers<T>(bridgeClass, name.c_str());

   bridgeClass.endClass()
      .endNamespace();
```

Now the code compiles, but when I run it, `assertStackState` fails on line 959 of Namespace.h.

**Comment by kunitoki** [comment]
Just stop at beginClass for the assignment.

The addXXX methods returns a reference, call them once you have a class object.

**Comment by rpatters1** [comment]
That fixed it.
