### ISSUE TITLE
problem with `std::function<void(int, std::string)>` argument

### ISSUE THREAD

**Issue by yEsPaP** [kunitoki/LuaBridge3#18]
trying to make a function exposed to lua that can add custom code to function
```
std::map<string, std::function<void(int, string)>> hooklist;
void Hook(std::string name, std::function<void(int, std::string)> cb) {
    hooklist.emplace(name, cb);
}
```

```
    lua_State* luaState = luaL_newstate();
    luaL_openlibs(luaState);
    luabridge::getGlobalNamespace(luaState).addFunction("Hook", &Hook);
    luaL_dofile(luaState, get_path(fileToEdit).string().c_str());
```

then in the function i'm "hooking"
```
    for (auto& func : hooklist) {
        func.second(type, packet);
    }
```

Lua script i did for test:
```
function hook1(type, packet)
log("lol")
end


Hook("hook1", hook1)
```

But if i try add debug statement in Hook() even it doesn't print, but if i remove `std::function<void(int, string)>` argument it works, but the whole purpose of code loses value. How could I make this work?

**Comment by yEsPaP** [comment]
by the way i tried using the luaref thing, but when i call the received function in c++ nothing happens for some reason

**Comment by kunitoki** [comment]
Don't know what you are doing wrong, but this works for me:

```cpp
    std::map<std::string, luabridge::LuaRef> hooklist;

    auto hook = [&](const std::string& name, luabridge::LuaRef cb) {
        hooklist.emplace(name, std::move(cb));
    };

    luabridge::getGlobalNamespace(L)
        .addFunction("Hook", hook);
    
    runLua(R"(
        function hook1(type, packet)
            print("lol")
        end

        Hook("hook1", hook1)
    )");

    for (auto& func : hooklist) {
        func.second(0, "x");
    }
```

**Comment by yEsPaP** [comment]
> Don't know what you are doing wrong, but this works for me:
> 
> ```c++
>     std::map<std::string, luabridge::LuaRef> hooklist;
> 
>     auto hook = [&](const std::string& name, luabridge::LuaRef cb) {
>         hooklist.emplace(name, std::move(cb));
>     };
> 
>     luabridge::getGlobalNamespace(L)
>         .addFunction("Hook", hook);
>     
>     runLua(R"(
>         function hook1(type, packet)
>             print("lol")
>         end
> 
>         Hook("hook1", hook1)
>     )");
> 
>     for (auto& func : hooklist) {
>         func.second(0, "x");
>     }
> ```

wow i just realised how stupid i am

instead of `func.second` i typed just `func` and neither compiler or me saw a problem

thank you .
