### ISSUE TITLE
How to get the name of a Lua variable?

### ISSUE THREAD

**Issue by Nolram12345** [kunitoki/LuaBridge3#186]
Hello! I'm trying to get the name of a Lua table/variable. For example:

Lua:
```lua
local myTestTable = {
    name = "Test",
    age = 20,
}

someCPPfunction(myTestTable)
```

C++:
```cpp
void someCPPfunction(lua_State* luaState) {
    luabridge::LuaRef table = luabridge::LuaRef::fromStack(luaState, 1);
    // How do I now get the name of the table, which is "myTestTable" ?
}
```

**Comment by Mellnik** [comment]
You should look into Lua's debug library. I think you can get the function via a stacktrace but even if it's possible to get a variable name it's not related to LuaBridge at all.

**Comment by Nolram12345** [comment]
Hmm... I'm using Luau, where the debug library doesn't exist :/ I thought that Luabridge might provide a way to accomplish this since it otherwise handles all intercommunications with Lua, but I guess not. I'll close this issue for now then...
