### ISSUE TITLE
Any reason to not merge with vinniefalco/LuaBridge?

### ISSUE THREAD

**Issue by timfel** [kunitoki/LuaBridge3#20]
I noticed there are some commits on the vinniefalco/LuaBridge repository that are not integrated here. Just curious: was there a particular reason not to integrate your changes into that repository?

**Comment by kunitoki** [comment]
I did initially wanted to contribute to it but i found that i could iterate faster by working on a separate fork and i needed those changes for my personal projects without also worrying on design decisions or be slowed down by breaking changes or code removals (i did remove some very unsafe and inefficient RefcountedPtr implementation).
