### ISSUE TITLE
Question about lifetime

### ISSUE THREAD

**Issue by timfel** [kunitoki/LuaBridge3#22]
So from the manual it reads as if any pointers returned to Lua will never be collected by Lua (delete will not be called on them), but copy-constructed objects will be. Is there any better way to control this? I want to be able to define two functions, and both should return a pointer to a newly constructed object. But one of the two objects is expected to be deleted by the C++ code later, and the other should be deleted when Lua decides to collect it. Is that possible, or am I thinking about this wrong?

**Comment by kunitoki** [comment]
Pass by pointer/ref expresses ownership by c++, while pass by copy will enablue lua ownership. In case you need shared ownership, i suggest you use reference counting, as it is the only way to ensure objects passed to lua are never destroyed from c++ if referenced by the vm and vice versa

**Comment by timfel** [comment]
Ok. The issue I had is that there are objects which have a constructor like this:
```c++
class SillyClass : SillyListener {
public:
    SillyClass() {
         listeners.push_back(this);
    }

    std::vector<SillyListener*> listeners;
}
```

I want to construct these and have them owned by Lua, but since they keep a pointer to themselves, the default copy constructor doesn't work. For now, I have worked around this by doing this:
```c++
            .addStaticFunction("__call", +[](lua_State *l) {
                int nargs = lua_gettop(l);
                luabridge::detail::UserdataValue<gcn::CheckBox>* value = luabridge::detail::UserdataValue<gcn::CheckBox>::place(l);
                switch (nargs) {
                    case 3:
                        new (value->getObject()) gcn::CheckBox(luabridge::Stack<std::string>::get(l, 2), luabridge::Stack<bool>::get(l, 3));
                        break;
                    default:
                        new (value->getObject()) gcn::CheckBox();
                        break;
                }
                value->commit();
                return 1;
            })
```

**Comment by kunitoki** [comment]
Make SillyListeners inhering from RefCountedObject, that way the ownership is shared and the refount will do the right job
