### ISSUE TITLE
bug:std::numeric_limits<U>::max C4003/min...

### ISSUE THREAD

**Issue by ImKK666** [kunitoki/LuaBridge3#27]
File:detail/LuaHelpers.h

func:
is_integral_representable_by
is_floating_point_representable_by

Error example:
```cpp
std::numeric_limits<U>::max()
std::numeric_limits<U>::min()
```
fix:
```cpp
(std::numeric_limits<U>::max)()
(std::numeric_limits<U>::min)()
```

**Comment by kunitoki** [comment]
Is this an issue when including windows.h without the macro that prevent min max from being defined?
