### ISSUE TITLE
Calling wrong function in Lua is getting only generic error "Error while calling ..."

### ISSUE THREAD

**Issue by eduardodoria** [kunitoki/LuaBridge3#31]
When I call some class method (or any function) in Lua with wrong arguments I always get this generic error:

> [string "lua://main.lua"]:89: Error while calling method
> stack traceback:
>         [C]: in method 'getSide'
>         [string "lua://main.lua"]:89: in main chunk

But If I comment this catch clause in FuncTraits.h:

```
catch (...)
{
    luaL_error(L, "Error while calling method");
}
```

 I get a more specific error:

> [string "lua://main.lua"]:89: bad argument #1 to 'getSide' (Vector3 expected, got table)
> stack traceback:
>         [C]: in method 'getSide'
>         [string "lua://main.lua"]:89: in main chunk

Which has much more information.

Is this intentional or am I doing something wrong?

**Comment by kunitoki** [comment]
It's very strange as of [c++ standard](https://en.cppreference.com/w/cpp/language/try_catch), the catch clauses are executed in order and will only fallback if not matching. We are throwing a `luabridge::LuaException` which is inherited from `std::exception`, so the first catch should kic in but it is somehow swallowed by the `catch (...)` for some reason i cannot explain. 

I've experienced this on Xcode, which platform and compiler are you using ?

**Comment by kunitoki** [comment]
Are you using the flag `-fprofile-arcs` ? found this old thread

https://stackoverflow.com/questions/9919500/catch-swallowing-all-other-catches-in-xcode-llvm-3-0

**Comment by kunitoki** [comment]
I've pushed https://github.com/kunitoki/LuaBridge3/commit/9c853dfe8aa0e30f7a3eefa81e389480ce3a3529 which should mitigate the issue while i figure it out

**Comment by eduardodoria** [comment]
Tested with Linux (GNU 11.2.0), Windows (MSVC 19.30) and Mac (Xcode 13.4.1).
Same error.

**Comment by kunitoki** [comment]
Can you test again against master?

**Comment by eduardodoria** [comment]
> Can you test again against master?

Tested and fixed.

Thanks!
