### ISSUE TITLE
An easy way to overload functions

### ISSUE THREAD

**Issue by eduardodoria** [kunitoki/LuaBridge3#36]
I recently migrated from Sol2 to Luabridge3 because this library is very lightweight, specially in compiling time. But Sol2 overload feature is fantastic.

In Luabridge3 I can do overload functions all manually, like these:

```
.addFunction("addVertex", +[](Polygon* self, lua_State* L) -> void { 
            if (lua_gettop(L) != 2 && lua_gettop(L) != 3) throw luaL_error(L, "incorrect argument number");
            if (lua_isnumber(L, 2) && lua_isnumber(L, 3)) self->addVertex(lua_tonumber(L, 2), lua_tonumber(L, 3));
            else if (luabridge::Stack<Vector3>::isInstance(L, -1)) self->addVertex(luabridge::Stack<Vector3>::get(L, -1));
            else throw luaL_error(L, "incorrect argument type");
            })
```

```
.addFunction("getBone", +[](Model* self, lua_State* L) -> Bone { 
            if (lua_gettop(L) != 2) throw luaL_error(L, "incorrect argument number");
            if (lua_isinteger(L, -1)) return self->getBone(lua_tointeger(L, -1));
            if (lua_isstring(L, -1)) return self->getBone(lua_tostring(L, -1));
            throw luaL_error(L, "incorrect argument type");
            })
```

It does the job but it is not easy as sol2.

I don't have much experience in modern C++ and I do not know if it is really possible. But would be interesting a template function like this pseudocode:

```
template<Ret, Func1, Func2, ...>
Ret overload(lua_State *L){
    if (lua_tointeger(L, 1))
        Func1(lua_tointeger(L, 1));

    if (lua_tostring(L, 1))
        Func2(lua_tostring(L, 1));
}
```

And use this in Luabridge to overload:

```
luabridge::getGlobalNamespace (L)
  .beginNamespace ("test")
    .addFunction ("foo", overload<(void (*)(int))&foo, (void (*)(std::string))&foo>)
  .endNamespace ();
```

Also I opened a question in Stackoverflow (https://stackoverflow.com/questions/73799816/how-overload-c-functions-in-lua-using-generic-function-template) about this.

**Comment by kunitoki** [comment]
Yes this is definately possible, but it will also add more complexity to the method resolution.

I have it planned for the future, after i stabilise the API of the Stack push and get to make them safe to be used from c++.

**Comment by eduardodoria** [comment]
I don't think you will need to change anything, just adding this template "overload" function. I will try to develop something. But if you thing it is not necessary this moment, you can close this.

**Comment by kunitoki** [comment]
I was just saying that before i can look into that one i need to first solve one problematic issue i have with LuaBridge which is unsafety of C++ calls it does, so many code paths leads to a `lua_error()` call which will call the panic handler when called from C++ and ends up raising an exception or worse having lua to call `std::abort` when exceptions are not enabled (we return from the panic handler). Once i've stabilized this PR https://github.com/kunitoki/LuaBridge3/pull/37 i will look into optional function overloads.

In that regard, there is an interesting discussion in this very very old (but still valid solution) vanilla LuaBridge ticket > https://github.com/vinniefalco/LuaBridge/issues/9

**Comment by kunitoki** [comment]
I pushed a WIP branch for initial work on the overloaded functions and method support https://github.com/kunitoki/LuaBridge3/pull/38 

It's based on the new push / get methods (https://github.com/kunitoki/LuaBridge3/pull/37) so you might have some issues dropping it in as it contains some breaking changes in the `Stack` api, and for now i've exposed only the Namespace and Class `addOverload` methods taking lambdas (it's not possible atm to mix and match function pointers, lua_CFunctions and lambdas in the same call to addOverload).

I decided to do a separate method in order to not overweight the normal addFunction methods with additional data (function arity) that is exclude method with non matching number of arguments.

```cpp
    int x = 100;

    luabridge::getGlobalNamespace(L)
        .addOverload("test",
            [x](int v) -> int {
                return v + x;
            },
            [x](std::string v) -> int {
                return v.size() ? int(v[0]) : x;
            });

    runLua("result = test (255)");
    ASSERT_TRUE(result().isNumber());
    EXPECT_EQ(355, result<int>());

    runLua("result = test ('')");
    ASSERT_TRUE(result().isNumber());
    EXPECT_EQ(100, result<int>());

    runLua("result = test ('0')");
    ASSERT_TRUE(result().isNumber());
    EXPECT_EQ(48, result<int>());
```

**Comment by eduardodoria** [comment]
Very fast solution :-)
I will test it as soon as possible.

The "problem" of separate method is you need to do for StaticFunction too, Namespace, Class and all variations. A lot of new methods may be me necessary. Instead of nested method option like `addFunction(addOverload(...))`.

May be name `addOverload` not the best IMO. Could be `addOverloadFunction` and `addOverloadStaticFunction`.

**Comment by kunitoki** [comment]
Yes i agree, but this is the first iteration. I'm working on unifying all the overloads into a single template overload that can catch all of them. I ame up with this (for namespace bound functions):

```cpp
    template <class... Functions>
    auto addFunction(const char* name, Functions... functions)
        -> std::enable_if_t<(detail::is_callable_v<Functions> && ...), Namespace&>
    {
        static_assert(sizeof...(Functions) > 0);

        assert(name != nullptr);
        assert(lua_istable(L, -1)); // Stack: namespace table (ns)

        if constexpr (sizeof...(Functions) == 1)
        {
            ([&]
            {
                detail::push_function(L, std::move(functions));
                rawsetfield(L, -2, name);

            } (), ...);
        }
        else
        {
            // create new closure of try_overloads with new table
            lua_createtable(L, static_cast<int>(sizeof...(Functions)), 0); // reserve space for N overloads

            int idx = 1;

            ([&]
            {
                lua_createtable(L, 2, 0); // reserve space for: function, arity
                lua_pushinteger(L, 1);
                lua_pushinteger(L, static_cast<int>(detail::function_arity_excluding_v<Functions, lua_State*>));
                lua_settable(L, -3);
                lua_pushinteger(L, 2);
                detail::push_function(L, std::move(functions));
                lua_settable(L, -3);

                lua_rawseti(L, -2, idx);
                ++idx;

            } (), ...);

            lua_pushcclosure_x(L, &detail::try_overload_functions, 1);
            rawsetfield(L, -2, name);
        }

        return *this;
    }
```

This allows to use a single method for registering both single functions, lambdas, CFunctions, and mixed overloads for all the above.

```cpp

.addFunction("name",
     &functionPointer,
     &functionPointerToLuaCFunction,
     [] {}, // non capturing lambda
     +[] {}, // non capturing lambda decayed to function pointer
     [capturing] {} // capturing lambda
);

```

**Comment by eduardodoria** [comment]
Awesome!
I am very happy with the replacement of Sol2 to Luabridge3. This was the missing feature.

**Comment by kunitoki** [comment]
I have some ideas that can speed up prioritising the most fitting overloads by using a similar technique to jni where the signature is encoded in string format (see https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html#wp276)

**Comment by kunitoki** [comment]
Yes overload resolution on c++ side is something i thought about as well and could be a path we investigate, but was a bit more convoluted in term of storage and retrieval, and depending if the methods are reused or not it will generate much more template instantiations.

**Comment by kunitoki** [comment]
I have been progressing a lot, we now have support in `Namespace` and `Class`, where `addFunction` `addStaticFunction` and `addConstructor` (the version taking functors) are allowed to take a single function or overloads passed in with a single function, supporting lua_CFunction, function pointers, member function pointers, capturing and non capturing lambdas and in general anything that is copyable and callable (std::function to name one example) !

**Comment by eduardodoria** [comment]
It is important to do it work first. After could try to improve performance as you said.

What are the plans to merge master branch?

**Comment by kunitoki** [comment]
I have plan to merge as soon as possible, but i would really like to write even more unit tests.

For now https://github.com/kunitoki/LuaBridge3/blob/f6adba327a19967b21857252369423ea4b4ece07/Tests/Source/OverloadTests.cpp is covering a wide variety of use cases already, but it's never too bad to add more checks, especially in an area like that.

For example i found that because of this code in the Stack https://github.com/kunitoki/LuaBridge3/blob/master/Source/LuaBridge/detail/Stack.h#L981-L1005 where we actually convert the argument to string, even if it's not of type string, an overload with string will basically "eat" any argument during resolution. I would say this is wrong and during function call / overload resolution, the behaviour of the Stack should be strict (but this means adding more flags, complexity).

**Comment by merlinblack** [comment]
Wow! Nice work :-) I use my own 'manualbind' now, which is a quite different beast, however it's great to see LuaBridge still being given some love :-D

**Comment by kunitoki** [comment]
Manualbind... sounds like a lot of work 🤣
