### ISSUE TITLE
Functions overload arity error

### ISSUE THREAD

**Issue by eduardodoria** [kunitoki/LuaBridge3#39]
I am trying to bind these functions:

```
Vector3 Vector3::operator * ( float f ) const{
    return Vector3(x * f, y * f, z * f);
}

Vector3 Vector3::operator * ( const Vector3& v ) const{
    return Vector3(x * v.x, y * v.y, z * v.z);
}
```

Using overload feature in `__mul` metamethod:

```
luabridge::getGlobalNamespace(L)
    ...
    .addFunction("__mul", (Vector3 (Vector3::*)(const Vector3&) const)&Vector3::operator*, (Vector3 (Vector3::*)(float) const)&Vector3::operator*)
    ...
    .endClass();
```

Testing this Lua code:

```
vec1 = Vector3(3,3,3)
vec2 = Vector3(2,2,2)

print(vec1 * 3)
print(vec1 * vec2)
```

And I'm getting this error only in `print(vec1 * vec2)` line:

_( ERROR ): Lua Error: All 2 overloads of mul returned an error:
1: Skipped overload #0 with unmatched arity of 0 instead of 1
2: Error decoding argument #2: The lua object can't be casted to desired type
stack traceback:
        [C]: in metamethod 'mul'
        [string "lua://main.lua"]:19: in main chunk_

I think function arity should be 1 but is registered with 0.

**Comment by eduardodoria** [comment]
In my case, removing `-1` in this part of code:

```
template <class T, class F, class... Ts, class ExclusionType>
struct member_function_arity_excluding<T, F, std::tuple<Ts...>, ExclusionType, std::enable_if_t<is_proxy_member_function_v<T, F>>>
    : std::integral_constant<std::size_t, (0 + ... + (std::is_same_v<std::decay_t<Ts>, ExclusionType> ? 0 : 1)) - 1>
{
};
```

To:

```
template <class T, class F, class... Ts, class ExclusionType>
struct member_function_arity_excluding<T, F, std::tuple<Ts...>, ExclusionType, std::enable_if_t<is_proxy_member_function_v<T, F>>>
    : std::integral_constant<std::size_t, (0 + ... + (std::is_same_v<std::decay_t<Ts>, ExclusionType> ? 0 : 1))>
{
};
```

It works!
But can break another part of code that I have not tested yet.

**Comment by kunitoki** [comment]
Is this a class function or global function ?

**Comment by kunitoki** [comment]
Ah i see now the issue, will apply a fix

**Comment by kunitoki** [comment]
Should be fixed in https://github.com/kunitoki/LuaBridge3/commit/36c8f8837fbd0f9708758c48848bab47119d703e

Could you verify it's ok on your end as well ? Added a unit test in the commit, would be nice if you can check if this is equal to your use case.

**Comment by kunitoki** [comment]
Btw now you can do:

```cpp
luabridge::getGlobalNamespace(L)
    ...
    .addFunction("__mul",
        luabridge::overload<const Vector3&>(&Vector3::operator*),
        luabridge::overload<float>(&Vector3::operator*))
    ...
    .endClass();
```

for even simpler overload resolution

**Comment by eduardodoria** [comment]
It is working now.
Thanks!
