### ISSUE TITLE
Documentation: return statement missing in 2.6.1 - Constructor Proxies

### ISSUE THREAD

**Issue by Cirromulus** [kunitoki/LuaBridge3#41]
In 2.6.1 - Constructor Proxies, all constructors that use functions are missing `return` statements, however these are necessary.
Otherwise works nicely, thanks

**Comment by kunitoki** [comment]
Those are indeed missing, will fix them asap.

Thanks for reporting!

**Comment by kunitoki** [comment]
Fixed in https://github.com/kunitoki/LuaBridge3/commit/b301220870514a31404059c91c27f2a3fd238d2c on master
