### ISSUE TITLE
PANIC: unprotected error in call to Lua API (bad light userdata pointer)

### ISSUE THREAD

**Issue by dtroitskiy** [kunitoki/LuaBridge3#42]
Hi!
I ran into a problem when recently I upgraded my project setup to use LuaJIT + LuaBridge 3.
To isolate it, I wrote a simple test:
```
#include "lua.hpp"
#include "LuaBridge.h"

class Test
{
public:
  static int sum(int x, int y)
  {
    return x + y;
  }
};

int main()
{
  auto L = luaL_newstate();
  luaL_openlibs(L);

  luabridge::getGlobalNamespace(L)
    .beginClass<Test>("Test")
      .addStaticFunction("sum", &Test::sum)
    .endClass();
}
```
And then I get the error stated in the title. It occurs as soon as `beginClass()` gets called.
Might be important to note here, that it doesn't occur with regular Lua and also it doesn't occur with LuaJIT + LuaBridge 2.8.
Also might be important that any other stuff I do works great, i.e. I can do `.beginNamespace()`, `addFunction()` etc. no problem. The error caused ONLY by `beginClass()` according to what I have tested so far.
LuaJIT version I used is 2.1.0-beta3, and I also noticed LuaBridge 3 tests running on that same LuaJIT version pass just fine, so I added this test code as a separate test in `ClassTests.cpp` and it worked correctly. So I suppose I'm not doing something important in Lua initialization, or maybe it's some `#define`'s I need, I'm not sure.

**Comment by dtroitskiy** [comment]
I figured out the problem for myself, but I think some fix / workaround may be necessary for LuaBridge 3 to work correctly with older versions of LuaJIT, so I'm not going to close this issue, I guess it's up to you to decide.
For me turned out the problem is in older version of LuaJIT I used at first.
I checked out this release tag https://github.com/LuaJIT/LuaJIT/releases/tag/v2.1.0-beta3
But only after some time I noticed it dates back to 2017. And version hasn't updated since then.
I noticed the difference when I built LuaBridge 3 tests and saw they all pass fine, including tests with class bindings.
When I started debugging, I noticed LuaJIT sources in tests are newer than those I used.
Then I built my test above with most recent LutJIT version, and it worked fine.
I think I even found the commit from which things start being different https://github.com/LuaJIT/LuaJIT/commit/e9af1abec542e6f9851ff2368e7f196b6382a44c#diff-b0f85e6abe34b72371a6e49cb1d454add64688dff45638eb90d67686fe36e6a6

As it's clearly stated in LuaBridge 3 docs it works with LuaJIT, I think it makes sense to either provide some fix for older versions or otherwise put some text like "works with most versions of LuaJIT".
Because for now, if you, for example, clone master branch, which contains v2.0.5, it won't work with LuaBridge 3, at least with class bindings.

**Comment by kunitoki** [comment]
Yeah the only supported version that is tested is 2.1.0-beta3 which is the last known release of LuaJIT. No other versions have been tested as of now, but i can try to repro the issue. Which platform are you on ?

Do you have an example that fails for you that i can try locally ? Also, can you post here your compilation flags ?

**Comment by dtroitskiy** [comment]
I'm on Linux.
Compilation flags are nothing specific, for this simple isolated example I used VSCode built-in C++ builder, so it's `-std=c++20 -g -O0` for the most part.
You can try the example I posted above. Basically, it doesn't matter what exact code you'll have there, as soon as you get to `beginClass()`, it will fail, because at some point `Class` constructor calls `lua_rawgetp()` and it in turn calls `lua_pushlightuserdata()`, and that's the point where after the commit I linked above it's implemented a bit differently.
For testing you can do `git checkout tags/v2.1.0-beta3` in the LuaJIT repo.

It's worth noting that here https://luajit.org/download.html it's said
> Releases are only made occasionally. You're strongly encouraged to follow the git branches.
So indeed author tells that release tags may be outdated. However, if it's easy to make a workaround of this issue, it may increase compatibility of LuaBridge with older versions and thus other users like me who want to use certain release of LuaJIT, won't fall into the same trap. If it will be hard to make a workaround, then I guess it can be left as is, only would be nice to add some comment to the docs about that.

**Comment by kunitoki** [comment]
I'm checking 2.0.5 and apparently it doesn't even support x86_64 target which is quite annoying.

**Comment by kunitoki** [comment]
i get issues even initialising luajit2.0.5 on my apple intel, it fails allocating the lua state:

```c

#if LJ_64
/* 64 bit mode needs special support for allocating memory in the lower 2GB. */

#if defined(MAP_32BIT)

#if defined(__sun__)
#define MMAP_REGION_START	((uintptr_t)0x1000)
#else
/* Actually this only gives us max. 1GB in current Linux kernels. */
#define MMAP_REGION_START	((uintptr_t)0)
#endif

static LJ_AINLINE void *CALL_MMAP(size_t size)
{
  int olderr = errno;
  void *ptr = mmap((void *)MMAP_REGION_START, size, MMAP_PROT, MAP_32BIT|MMAP_FLAGS, -1, 0); // Fails here 
  errno = olderr;
  return ptr;
}

```

**Comment by kunitoki** [comment]
I also tested a standalone build, compiled luajit 2.0.5 from source using the makefile, then created this program:

```cpp
#include "src/lua.hpp"

class Test
{
public:
  static int sum(int x, int y)
  {
    return x + y;
  }
};

int main()
{
  auto L = luaL_newstate();
  luaL_openlibs(L);
}
```
and then compile it and launch it:
```
lucio.asnaghi@BARLTM8WMD6T1 LuaJIT.2.0.5 (master) $ g++ -std=c++17 test.cpp -Lsrc/ -lluajit
lucio.asnaghi@BARLTM8WMD6T1 LuaJIT.2.0.5 (master) $ lldb
(lldb) target create a.out
Current executable set to '/Users/kunitoki/LuaBridge3/Tests/Lua/LuaJIT.2.0.5/a.out' (x86_64).
(lldb) run
Process 42712 launched: '/Users/kunitoki/LuaBridge3/Tests/Lua/LuaJIT.2.0.5/a.out' (x86_64)
Process 42712 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x000000010013260b libluajit-5.1.2.dylib`lua_pushcclosure + 16
libluajit-5.1.2.dylib`lua_pushcclosure:
->  0x10013260b <+16>: movl   0x8(%rdi), %eax
    0x10013260e <+19>: movl   0x20(%rax), %ecx
    0x100132611 <+22>: cmpl   0x24(%rax), %ecx
    0x100132614 <+25>: jae    0x1001326d1               ; <+214>
Target 0: (a.out) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
  * frame #0: 0x000000010013260b libluajit-5.1.2.dylib`lua_pushcclosure + 16
    frame #1: 0x0000000100137818 libluajit-5.1.2.dylib`luaL_openlibs + 31
    frame #2: 0x0000000100003f7a a.out`main + 26
    frame #3: 0x00007fff2090cf3d libdyld.dylib`start + 1
    frame #4: 0x00007fff2090cf3d libdyld.dylib`start + 1
```

🤷🏻

**Comment by kunitoki** [comment]
Can you check if commenting these it works ?

```
inline void lua_rawgetp(lua_State* L, int idx, const void* p)
{
    idx = lua_absindex(L, idx);
    // luaL_checkstack(L, 1, "not enough stack slots"); // comment this one
    lua_pushlightuserdata(L, const_cast<void*>(p));
    lua_rawget(L, idx);
}

inline void lua_rawsetp(lua_State* L, int idx, const void* p)
{
    idx = lua_absindex(L, idx);
    // luaL_checkstack(L, 1, "not enough stack slots"); // and this
    lua_pushlightuserdata(L, const_cast<void*>(p));
    lua_insert(L, -2);
    lua_rawset(L, idx);
}
```

**Comment by kunitoki** [comment]
https://github.com/LuaJIT/LuaJIT/issues/521#issuecomment-562999247

**Comment by Erza** [comment]
> [LuaJIT/LuaJIT#521 (comment)](https://github.com/LuaJIT/LuaJIT/issues/521#issuecomment-562999247)
> 
> i'm considering closing the bug and making clear that we only support 2.1 onwards

Makes no sense, since he used the 2.1.0-beta3 release tag. The problem is that this release tag is from 2017, and there have been changes to the master branch since then that made his issue go away, but no new release tag has been created since.

**Comment by kunitoki** [comment]
If you use luajit 2.1 branch instead, there should be no problem there, as Mike is saying. He stated it multiple times, use branches and avoid tags...

**Comment by Erza** [comment]
Yeah, obviously @dtroitskiy already said that earlier. The problem that's being reported is that LuaBridge3 has an issue with the release tag, while the original LuaBridge does not, that's what this is about.

**Comment by kunitoki** [comment]
Ok but regardless of luabridge or luabridge3, i can't even start a simple luajit program on my 64bit processor on any of the luajit tags 🤷🏻

**Comment by kunitoki** [comment]
@dtroitskiy can you try with https://github.com/kunitoki/LuaBridge3/pull/45 ? it seems like older luajit versions are not able to store full 64bits pointers in lightuserdata (only supported are the first 47 bits), trying to feed anything bigger will result into a runtime fail.

**Comment by dtroitskiy** [comment]
Sorry for waiting my reply.
Just tested this couple times with and without fix just to be sure - fix works for me. Good job!
Additionally checked that works both with LuaJIT 2.0.5 and v2.1.0-beta3 release tag.

By the way, not sure if relevant anymore, but I have no problems using older versions of LuaJIT in x64 builds, as I assume in modern Linux they're produced by default by gcc / clang. No problems for me with initializing state and such.
But from your message I suppose you're on Mac OS, so there may be some differences.
