### ISSUE TITLE
Update to modern Luau version (0.55x)?

### ISSUE THREAD

**Issue by DezlowNG** [kunitoki/LuaBridge3#44]
Hello!

Why you don't update luau to new versions? I need to use a modern luau with bug fixes and new features, but LuaBridge written with using Luau 0.50x.

Thanks!

**Comment by kunitoki** [comment]
Contributions welcome!

**Comment by kunitoki** [comment]
I have zero issues running with luau 0.556 had to change zero headers from luabridge. once adopted the unit tests builds (mainly because they moved files around in their compiler), all of them pass with no failures:

```
[==========] 537 tests from 134 test suites ran. (417 ms total)
[  PASSED  ] 537 tests.
```

i've updated master to use the new upstream tag.
