### ISSUE TITLE
Why LuaRef calls function after closing the application?

### ISSUE THREAD

**Issue by DezlowNG** [kunitoki/LuaBridge3#48]
Hello!

I added ScriptComponent to my ecs abstraction and I call OnCreate function when user add ScriptComponent to entity, but lua function not calls in runtime (but calls when app closing).

![img1](https://user-images.githubusercontent.com/74720936/210121688-c65550bb-3936-478f-bab6-135e038b6bd9.png)
![img2](https://user-images.githubusercontent.com/74720936/210121698-e6b5bc63-9a23-4f8b-a3c8-b03a8bf36bc4.png)
![img3](https://user-images.githubusercontent.com/74720936/210121713-32614943-4994-442a-bc9d-255c616ab6c2.png)
![img4](https://user-images.githubusercontent.com/74720936/210121733-82e86006-0ad5-42b3-a659-1bc154051e4c.png)
![img5](https://user-images.githubusercontent.com/74720936/210121763-87050e94-7724-4810-87c3-66559a6dd829.png)

**Comment by DezlowNG** [comment]
I use spdlog for logging, but lua use standart cout func.

**Comment by kunitoki** [comment]
You can easily register a `print` method in the global lua namespace using luabridge3 that will call spdlog instead of printf
