### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by dtroitskiy** [kunitoki/LuaBridge3#55]
And here I come with another issue =)
This one was actually discovered by me some time ago, but I wasn't sure it's worth posting, now decided it probably is, because maybe it can be improved.

So, I started using LuaBridge 3 after LuaBridge 2.8, and in 2.8 version it was supposed to add `Stack` specializations for enums this way https://github.com/vinniefalco/LuaBridge/issues/204
When I started using LuaBridge 3, it was stated in the docs that now it's done this way:
"Automatic handling of enum types by communicating with lua through std::underlying_type_t".
And indeed quite soon I found out that you can bind enum values as namespace properties and in Lua they turn into numbers basically. And I'm talking about both usual `enum` and and `enum class`. So I just wrote an example to double-check that, goes this way:
```
enum Enum
{
	ONE,
	TWO,
	THREE
};

enum class EnumClass
{
	One,
	Two,
	Three
};

// Then in bindings:

getGlobalNamespace(L)
  .beginNamespace("Enum")
    .addProperty("ONE", ONE)
    .addProperty("TWO", TWO)
    .addProperty("THREE", THREE)
  .endNamespace()
  .beginNamespace("EnumClass")
    .addProperty("One", EnumClass::One)
    .addProperty("Two", EnumClass::Two)
    .addProperty("Three", EnumClass::Three)
  .endNamespace()
```
And then in Lua you can just do `print(Enum.ONE)` or `print(EnumClass.One)` and it will print 0.
Though here along the way I may express a wish that instead of `beginNamespace()` maybe it would be better to have `beginEnum()` to have more descriptive syntax, but that's minor thing.

So the problem appears when, for example, you try to pass this enum value to some function like this:
```
// C++
void testEnumAsArg(Enum value)
{
	printf("Enum value: %i.\n", value);
}
```
```
-- Lua
testEnumAsArg(Enum.One)
```
Doesn't matter whether it's `enum` or `enum class`, it will fail with this error:
`bad argument #1 to 'testEnumAsArg' (unregistered class expected, got number)`.

Then turns out that `Stack` specialization works, only it needs to be updated to LuaBridge 3 specifics like `Result` / `TypeResult` stuff etc. I think I'll omit code example here, I will share a link to full example again. With that wrapper I can do it like this:
```
template <>
struct Stack<Enum> : LuaEnumClassWrapper<Enum>
{
};
```
And then passing enum as argument starts working as expected.

A quite frustrating thing may happen when you don't even get any meaningful error and it just doesn't work.
That's the case when you create `std::map` when enum is used as key, like this:
```
std::map<Enum, std::string> testEnumMap = {
	{ ONE, "ONE" },
	{ TWO, "TWO" },
	{ THREE, "THREE" }
};
```
Then, if you bind this map (with the help of `#include "LuaBridge/Map.h"`, of course), and try to access it in Lua, you just get an error without any description.
Though if instead you change `map` declaration to this `std::map<int, std::string>` it will work just fine.

So, initially I thought "well, I'm just going to use these wrappers", but now I started to think it's probably possible to do some automatic conversion here without using them. Because if it basically works C++ => Lua way, it should work the other way around.
If there are some complications, then I can continue use these wrappers just fine.

Full code example is here https://www.dropbox.com/s/ew7fahendv2z6xr/EnumClassTest.zip?dl=0. Wrappers are on line 30 of `main.cpp`, if you comment them, you get errors I'm talking about.

**Comment by kunitoki** [comment]
Yeah there is no special way to declare enums as types and the only way is still the old way (a stack specialization is required). The underlying type usage is just to simplify passing enums from c++ down to lua.

I'm fine having a more structured type definition for enums, where a c++ enum could be mapped to a lua one, and offer more transparent bidirectional conversion. Will look into it, thanks for reporting !

**Comment by dtroitskiy** [comment]
Ah, I see, then I will continue to use stack specializations.
And I guess you can close this issue whenever you feel like it.

**Comment by dtroitskiy** [comment]
Oh, right, one thing that would be definitely nice to fix is that case when you use it as `std::map` key and similar, because, like I described, there is no error message at all, and would be nice to have something similar to error you get when you try to use it as function call argument, thus at least you understand what's going on wrong more clearly.

**Comment by kunitoki** [comment]
I'm working on adding proper enum support in the library

**Comment by kunitoki** [comment]
It's kind of difficult to chose a single way to handle this, because depending on the use case this could get implemented in different ways (which might also have performance considerations). 

There are two possibilities:

- treat C++ enums as integers, and map them to lua as such. it will work but passing any unrelated lua integer to a C++ function taking an enum, it will work (even if the integer conversion can't assume a valid enum value). This is the fastest, but also the less secure (UB is just behind the corner).

- treat C++ as userdata. Enums will have their own type on the lua side so they can be checked (you can's just `call(1)` from lua to a method exposed in C++ that takes a `call(enum_type value)`, you need to use a valid userdata. This is the safest (in term of type safety) but also the slowest.

I'm considering allowing both.

**Comment by kunitoki** [comment]
I've pushed both wrappers for Stack, see https://github.com/kunitoki/LuaBridge3/pull/56 

In the meanwhile i'll add docs, it would be nice if you could check if they help.

**Comment by kunitoki** [comment]
After trying more with the second solution, i think there are some caveats, will investigate

**Comment by kunitoki** [comment]
It doesn't seem we can workaround this with enums as separate types with their own userdata:

```
The indexing of tables follows the definition of raw equality in the language. The expressions a[i] and a[j] denote the same table element if and only if i and j are raw equal (that is, equal without metamethods). In particular, floats with integral values are equal to their respective integers (e.g., 1.0 == 1). To avoid ambiguities, any float with integral value used as a key is converted to its respective integer. For instance, if you write a[2.0] = true, the actual key inserted into the table will be the integer 2. (On the other hand, 2 and "2" are different Lua values and therefore denote different table entries.)
```

Full userdata cannot be used for indexing (every time you create an "instance" of the userdata, it will be a different object only raw equal to itself), so your example will never work when enums are mapped to userdata:
```
std::map<Enum, std::string> testEnumMap = {
	{ ONE, "ONE" },
	{ TWO, "TWO" },
	{ THREE, "THREE" }
};
```

We could use lightuserdata by hashing the enum type + value, but there are hight chances of hash collisions between enums.

**Comment by dtroitskiy** [comment]
Ok, so as I understand, first solution, i.e. "treat C++ enums as integers" would be in favor right now?
Yeah, second one sounded a bit more more correct to me, I'd say, but if it's problematic, then first also works for me no problem.
If, thanks to stack specializations, type conversion will always work fine when calling something Lua => C++, then it sounds good enough.

**Comment by kunitoki** [comment]
See this discussion http://lua-users.org/lists/lua-l/2007-01/msg00126.html apparently the only way is to implement a userdata cache in the form of weak table in the registry that will return references to existing userdata instances when they are already there, or being populated when not there. Sounds interesting but it's also a bit demanding both in term of space and time complexity.

**Comment by dtroitskiy** [comment]
I see. Despite that I'm not too good in Lua C API internals, I understand more or less what is discussed there.
Well, okay, I leave this entirely up to you to decide. If you find time to experiment with this userdata cache, then it has a chance to provide some decent outcome or at least some useful experience, I guess. Alternatively, like I said, using stack specializations is not a problem for me personally, although yeah, it's a bit of additional manual work, but not too much.

**Comment by kunitoki** [comment]
I found a way to make sure the conversion can be made. It's a bit more tedious, but i've now moved the enum wrapper class for stack into the library, so you should write:

```cpp

enum class MyEnum
{
    A,
    B,
    C
};

template <>
struct luabridge::Stack<EnumType> : luabridge::Enum<EnumType,
                                                    EnumType::A,
                                                    EnumType::B,
                                                    EnumType::C>
{
};
```

This way i can check in Stack::get that the passed integer is convertible to one of the mapped enum values, and if not present raise a lua error.

**Comment by kunitoki** [comment]
Yeah i noticed i did some mistakes in the manual, will try to fix them asap

**Comment by kunitoki** [comment]
https://github.com/kunitoki/LuaBridge3/pull/58
https://github.com/kunitoki/LuaBridge3/pull/59
