### ISSUE TITLE
Wrong type in arg error message

### ISSUE THREAD

**Issue by Mellnik** [kunitoki/LuaBridge3#67]
1. Expose a function to Lua from C++ with 1 argument of a userdata type.
2. Call the function from Lua but do not pass any value.
3. Error message says it got ``table``.

It should rather print that it got ``no value``.

``` [string "testscript"]:X: bad argument #1 to 'MyFunction' (SOMETYPE expected, got table)```

Problem lies around ``Userdata::throwBadArg``, it prints table because the metatable of the userdata is on the stack.

**Comment by kunitoki** [comment]
the problem is that if you are not passing an argument, there is no lua value (in this case i would expect a nil) on the stack

**Comment by Mellnik** [comment]
But should it really say ``nil``? What if a user passes an actual ``nil``?

What do you think about this one. I've added 4 pops to get ``no value`` in the message. See comments.
```C++
static Userdata* throwBadArg(lua_State* L, int index)
{
	assert(lua_istable(L, -1) || lua_isnil(L, -1));

	const char* expected = 0;
	if (lua_isnil(L, -1))
	{
		expected = "unregistered class";
	}
	else
	{
		lua_rawgetp(L, -1, getTypeKey());
		expected = lua_tostring(L, -1);
		lua_pop(L, 1); // lua_rawgetp(L, -1, getTypeKey());
	}

	const char* got = 0;
	if (lua_isuserdata(L, index))
	{
		lua_getmetatable(L, index);
		if (lua_istable(L, -1))
		{
			lua_rawgetp(L, -1, getTypeKey());
			if (lua_isstring(L, -1))
			{
				got = lua_tostring(L, -1);				
				lua_pop(L, 1); // lua_rawgetp(L, -1, getTypeKey());
			}
			lua_pop(L, 1); // lua_getmetatable(L, index);
		}
	}

	if (!got)
	{
		lua_pop(L, 1); // lua_rawgetp(L, LUA_REGISTRYINDEX, registryClassKey); from getClass
		got = lua_typename(L, lua_type(L, index));
	}

	luaL_argerror(L, index, lua_pushfstring(L, "%s expected, got %s", expected, got));
	return nullptr;
}
```

**Comment by kunitoki** [comment]
Yeah looks great

**Comment by kunitoki** [comment]
Pushed your version and some unit tests in https://github.com/kunitoki/LuaBridge3/pull/69

**Comment by kunitoki** [comment]
It seems like i canno merge the changes you propose, the code coverage job fails (during gcda merging). Not sure what's wrong, will try rewriting a new test
