### ISSUE TITLE
Support different assert macros.

### ISSUE THREAD

**Issue by Mellnik** [kunitoki/LuaBridge3#71]
Some project's have their own implementation of ``assert``.
What do you think of replacing all of them with a macro which can be overridden.

```C++
#ifndef LUABRIDGE_ASSERT
#define LUABRIDGE_ASSERT assert
#endif
```
Example from ImGui: https://github.com/ocornut/imgui/blob/master/imconfig.h#L19

**Comment by kunitoki** [comment]
Yes i have this in other projects, but instead of a macro i have a function called `expect(condition)`
