### ISSUE TITLE
New release/tag

### ISSUE THREAD

**Issue by hasore** [kunitoki/LuaBridge3#77]
Please, add a new release or tag for project, theres a considerable number of changes since 3.0-rc1.
Asking for that due vcpkg and conan.

**Comment by kunitoki** [comment]
Yes this is something i would like to improve. Just wanted to wait for any potential new breaking change. Will try to make an official release this week.

**Comment by kunitoki** [comment]
https://github.com/microsoft/vcpkg/pull/30493 in the queue

**Comment by kunitoki** [comment]
@hasore are you doing anything for conan ? i would like to add support for it, but not sure what is required.

**Comment by hasore** [comment]
No, i just mentioned it.

**Comment by kunitoki** [comment]
Merged in vcpkg upstream
