### ISSUE TITLE
There's a small problem

### ISSUE THREAD

**Issue by jphz** [kunitoki/LuaBridge3#8]
// cpp code
// UserdataPtr Can't call
luabridge::LuaRef func = luabridge::getGlobal(L, func_name);
luabridge::LuaResult result = func("helloworld");

// const char* yes
luabridge::LuaRef func = luabridge::getGlobal(L, func_name);
const char* str = "helloworld";
luabridge::LuaResult result = func(name);

// lua code
function test(args)
    print(args)
end

**Comment by kunitoki** [comment]
What is exactly the problem you have?

**Comment by jphz** [comment]
call func("helloworld") faild                call func(name) success

**Comment by kunitoki** [comment]
Fixed on the latest master
