### ISSUE TITLE
Weird issue with inheritance tree (LB3 only)

### ISSUE THREAD

**Issue by rpatters1** [kunitoki/LuaBridge3#97]
### Intro

I have begun to investigate migrating my project from LB2 to LB3, and my regression test script (which is extensive) has surfaced exactly two issues that are extremely puzzling and random. One of them I haven't even thought of how to investigate, so I am tackling the other first. (Perhaps they have the same root cause: a man can dream.) I don't have a reproducible test case, but I was hoping @kunitoki or anyone else might have an idea as to where to start digging.

### Executive summary

I have a class that (apparently) due to its name is generating a runtime error in LB3 but not in LB2. All my efforts to identify this problem have failed. Any ideas for how to proceed would be most welcome.

### Sample class for context (does not fail)

My problem class is in an inheritance tree similar to the following. (The following works. I am just providing it for context so that I can describe the technical details of the problem.)

```c++
struct basebase {};

struct barbase : basebase
{
   virtual int foobar(int a, int b) { return a + b; }
};

struct foobase : basebase
{
   virtual int foobar(int a) { return a; }
};

struct foo : foobase {};
```
And it is registered like this:

```c++
   luabridge::getGlobalNamespace(L)
      .beginNamespace("foobar")
         .beginClass<basebase>("basebase")
         .endClass()
         .deriveClass<barbase, basebase>("barbase")
            .addFunction("foobar", &barbase::foobar)
         .endClass()
         .deriveClass<foobase, basebase>("foobase")
            .addFunction("foobar", &foobase::foobar)
         .endClass()
         .deriveClass<foo, foobase>("foo")
            .addConstructor<void(*) (void)>()
         .endClass()
      .endNamespace();
```

With *my* class (not the above example), when I run this Lua code, it fails as shown:

```lua
local foo = foobar.foo()
local rslt = foo:foobar(3)
--runtime error: Error decoding argument #3: The lua object can't be cast to desired type
```

### What I know

I have done extensive debug tracing, and here is what I know:

- The problem occurs on both platforms I use: macOS XCode and Windows Visual Studio 2022.
- `foobar()` is failing because when Lua retrieves its function pointer from the Lua stack, the pointer has been miscast to `barbase::foobar` which takes two arguments instead of one.
- Though miscast, the function pointer address is correct. If I supply two integer arguments in Lua, LB3 lets the function call go through, and the correct function (`foobase::foobar`) is called (which only sees the first argument).
- The function is registered with the correct type. (I have traced into `addFunction` to confirm this.)
- None of this happens when compiled with LB2. Lua retrieves the correctly cast function pointer from the Lua stack, and the function executes without issues.

### What I tried

I have dozens of other classes registered in exactly this same manner. None of them (that I've found) have this problem. It is something specific to this class.

- I have removed all the function registrations from my class and still see the problem.
- I have bypassed my registration function and registered it with direct calls to the luabridge API and still see the problem.
- I even cannibalized the class by removing as much of it as I could without a major rewrite and still saw the problem.
- I created a superclass of my class and the superclass has the same problem.
- I made a copy of the class and replaced all internal references to my class to the replacement copy (or as many as the compiler reported) . The copy does *not* fail.

### What finally made a (very weird) difference

- I went back to a clean version of my code and simply renamed the class using global search and replace. The renamed class does *not* fail. (!)
- I named the class back to the original name (with global search and replace, not with git) and it *fails* again. (!)
- Simply changing the registration name in LuaBridge made no difference. I had to change the actual class name.
- The reverse is also true. With the renamed class that works, I registered it in LB under the original class name. That also works.
- A new minimal class with my problem class's name (`FCStaffSystem`) does not exhibit the problem.

### Conclusion

This problem is related to the actual class name and not its registered name in LB. But why this particular class name is causing this failure has stumped me.

**Comment by kunitoki** [comment]
I'm guessing it's because of the new LB3 hashing of classnames.

**Comment by kunitoki** [comment]
Are thos your effective class names ? Can you provide me the real names ?

**Comment by rpatters1** [comment]
I am away from my dev box at the moment, but here is a skeleton version off the top of my head:

```c++
class __FCBase {};
class __FCBaseData : public __FCBase {};
class __FCOther : public __FCBaseData {};
class __FCInciOther : public __FCOther {};
class __FCNoInciOther : public __FCOther {};
class FCStaffSystem : public __FCNoInciOther {}; // this is the problem class
class FCSystemStaff : public __FCInciOther {}: // possible conflict?
```

If you need to fill it in further, the full class hierarchy is explorable [here](https://pdk.finalelua.com/class_f_c_staff_system.html). There are other classnames in the hierarchy that might fool a hash, such as `FCSystemStaff` and `FCStaffSystems`. In fact, if I had to put money on the one that is the problem, it would `FCSystemStaff` (same letters, different order.) I added it above.

**Comment by kunitoki** [comment]
There was indeed a bug in the class name hashing. Pretty bad, sorry for the issue. Will be merged shortly.

**Comment by rpatters1** [comment]
I can confirm that your modification for this fixes my issue.
