### ISSUE TITLE
Invalid noexcept operator

### ISSUE THREAD

**Issue by Mellnik** [kunitoki/LuaBridge3#99]
The following function in Expected.h is marked as `noexcept` but throws if `LUABRIDGE_HAS_EXCEPTIONS` is true.

```C++
constexpr const T&& value() const&& noexcept
{
#if LUABRIDGE_HAS_EXCEPTIONS
	if (!hasValue())
		throw BadExpectedAccess<E>(error());
#endif

	return std::move(base_type::value());
}
```

**Comment by kunitoki** [comment]
Thanks for reporting, will fix those. I'm in the process of addressing those issues as reported by sonar, but haven't finished sonar integration yet.
